// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieApp.Data.Models;

public partial class Actor
{
    public long ActorId { get; set; }

    public string ActorName { get; set; }

    public DateOnly? BirthDate { get; set; }

    public string Bio { get; set; }

    public virtual ICollection<MovieActor> MovieActors { get; set; } = new List<MovieActor>();
}