// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieApp.Data.Models;

public partial class MovieSeason
{
    public long SeasonId { get; set; }

    public long MovieId { get; set; }

    public string SeasonName { get; set; }

    public string PosterUrl { get; set; }

    public int ReleaseYear { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual ICollection<MovieEpisode> MovieEpisodes { get; set; } = new List<MovieEpisode>();

    public virtual ICollection<UserWatchHistory> UserWatchHistories { get; set; } = new List<UserWatchHistory>();
}