// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieApp.Data.Models;

public partial class MovieRate
{
    public long Id { get; set; }

    public long MovieId { get; set; }

    public long UserId { get; set; }

    public long? Vote { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual User User { get; set; }
}