// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieApp.Data.Models;

public partial class MovieType
{
    public long TypeId { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();
}