// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieApp.Data.Models;

public partial class User
{
    public long UserId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Passwordhash { get; set; }

    public long RoleId { get; set; }

    public long StatusId { get; set; }

    public bool IsVerified { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<MovieRate> MovieRates { get; set; } = new List<MovieRate>();

    public virtual UserRole Role { get; set; }

    public virtual UserStatus Status { get; set; }

    public virtual ICollection<UserLike> UserLikes { get; set; } = new List<UserLike>();

    public virtual UserToken UserToken { get; set; }

    public virtual ICollection<UserVerification> UserVerifications { get; set; } = new List<UserVerification>();

    public virtual ICollection<UserWatchHistory> UserWatchHistories { get; set; } = new List<UserWatchHistory>();
}