// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieApp.Data.Models;

public partial class UserWatchHistory
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public long? MovieId { get; set; }

    public DateTime? WatchAt { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual User User { get; set; }
}