// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieApp.Data.Models;

public partial class UserWatchHistory
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public long? MovieId { get; set; }

    public long? SeasonId { get; set; }

    public long? EpisodeId { get; set; }

    public DateTime? LastWatch { get; set; }

    public long? TimeWatch { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual MovieSeason Season { get; set; }

    public virtual MovieEpisode Episode { get; set; }

    public virtual User User { get; set; }
}